services:
  - type: web
    name: noir-backend
    env: docker
    repo: https://github.com/rylsherdamz-rgb/Noir_Wallet
    branch: main
    dockerfilePath: backend/asset/backend/Dockerfile
    dockerContext: backend/asset
    healthCheckPath: /health
    envVars:
      - key: STELLAR_NETWORK
        value: testnet
      - key: STELLAR_HORIZON_URL
        value: https://horizon-testnet.stellar.org
      - key: STELLAR_RPC_URL
        value: https://soroban-testnet.stellar.org
      - key: STELLAR_NETWORK_PASSPHRASE
        value: Test SDF Network ; September 2015
      - key: RUST_LOG
        value: info
      - key: DATABASE_URL
        sync: false
      - key: MASTER_KEY_ID
        sync: false
      - key: CHANNEL_SECRET_KEY
        sync: false
      - key: ISSUER_ADDRESS
        sync: false
      - key: PDAX_API_KEY
        sync: false
      - key: PDAX_SECRET_KEY
        sync: false
      - key: PDAX_CLIENT_ID
        sync: false
      - key: TERMINAL_ID
        sync: false
