// Expo config plugin: skip Android Lint's release-time "lintVital" pass.
//
// `lintVitalAnalyzeRelease` runs during `assembleRelease` even with `-x lint`,
// and AGP's lint can crash on third-party module sources (e.g. :expo's
// ReactActivityDelegateWrapper.kt hits an ArrayIndexOutOfBoundsException in
// PrivateApiDetector's ApiDatabase). That is a lint bug, not an app bug, and it
// fails the whole release build. android/ is regenerated by prebuild, so the
// override lives here instead of in android/build.gradle.
const { withProjectBuildGradle } = require('expo/config-plugins')

const MARKER = '// @noir/disable-release-lint'

const SNIPPET = `
${MARKER}
subprojects { p ->
  p.tasks.matching { it.name.startsWith('lintVital') }.configureEach { enabled = false }
}
`

module.exports = function withDisableReleaseLint(config) {
  return withProjectBuildGradle(config, (cfg) => {
    if (cfg.modResults.language === 'groovy' && !cfg.modResults.contents.includes(MARKER)) {
      cfg.modResults.contents += SNIPPET
    }
    return cfg
  })
}
